// Generated on 2025-03-08T16:59:22.511Z
import { App } from "../generated/models/App.ts";
import { Table } from "../generated/models/Table.ts";
import { ReportRunResponse } from "../generated/models/ReportRunResponse.ts";
import { Field } from "../generated/models/Field.ts";
import { Record } from "../generated/models/Record.ts";
import { Upsert200Response } from "../generated/models/Upsert200Response.ts";
import { GetTempTokenDBID200Response } from "../generated/models/GetTempTokenDBID200Response.ts";

export interface QuickbaseClient {
  createApp: (params: { generated?: any }) => Promise<any>;
  getApp: (params: { appId: string }) => Promise<App>;
  getAppEvents: (params: { appId: string }) => Promise<any[]>;
  copyApp: (params: { appId: string; generated?: any }) => Promise<any>;
  getAppTables: (params: { appId: string }) => Promise<Table[]>;
  getTable: (params: { appId: string; tableId: string }) => Promise<any>;
  updateTable: (params: { appId: string; tableId: string; generated?: any }) => Promise<any>;
  deleteTable: (params: { appId: string; tableId: string }) => Promise<any>;
  getRelationships: (params: { skip?: number; tableId: string }) => Promise<any>;
  createRelationship: (params: { tableId: string; generated?: any }) => Promise<any>;
  updateRelationship: (params: { tableId: string; relationshipId: any; generated?: any }) => Promise<any>;
  deleteRelationship: (params: { tableId: string; relationshipId: any }) => Promise<any>;
  getTableReports: (params: { tableId: string }) => Promise<any[]>;
  getReport: (params: { tableId: string; reportId: string }) => Promise<any>;
  runReport: (params: { reportId: string; generated: any }) => Promise<ReportRunResponse[]>;
  getFields: (params: { tableId: string; includeFieldPerms?: boolean }) => Promise<Field[]>;
  getField: (params: { tableId: string; includeFieldPerms?: boolean; fieldId: number }) => Promise<any>;
  updateField: (params: { tableId: string; fieldId: number; generated?: any }) => Promise<any>;
  getFieldsUsage: (params: { tableId: string; skip?: number; top?: number }) => Promise<any[]>;
  getFieldUsage: (params: { tableId: string; fieldId: number }) => Promise<any[]>;
  runFormula: (params: { generated?: any }) => Promise<any>;
  upsert: (params: { generated?: any }) => Promise<any>;
  deleteRecords: (params: { generated?: any }) => Promise<any>;
  upsertRecords: (params: { generated: Record[] }) => Promise<Upsert200Response[]>;
  getTempTokenDBID: (params: { dbid: string }) => Promise<GetTempTokenDBID200Response>;
  exchangeSsoToken: (params: { generated?: any }) => Promise<any>;
  cloneUserToken: (params: { generated?: any }) => Promise<any>;
  transferUserToken: (params: { generated?: any }) => Promise<any>;
  deactivateUserToken: (params: {  }) => Promise<any>;
  deleteUserToken: (params: {  }) => Promise<any>;
  downloadFile: (params: { tableId: string; recordId: number; fieldId: number; versionNumber: number }) => Promise<any>;
  deleteFile: (params: { tableId: string; recordId: number; fieldId: number; versionNumber: number }) => Promise<any>;
  getUsers: (params: { accountId?: any; generated?: any }) => Promise<any>;
  denyUsers: (params: { accountId?: any; generated?: string[] }) => Promise<any>;
  denyUsersAndGroups: (params: { accountId?: any; shouldDeleteFromGroups: boolean; generated?: string[] }) => Promise<any>;
  undenyUsers: (params: { accountId?: any; generated?: string[] }) => Promise<any>;
  addMembersToGroup: (params: { gid: any; generated?: string[] }) => Promise<any>;
  removeMembersFromGroup: (params: { gid: any; generated?: string[] }) => Promise<any>;
  addManagersToGroup: (params: { gid: any; generated?: string[] }) => Promise<any>;
  removeManagersFromGroup: (params: { gid: any; generated?: string[] }) => Promise<any>;
  addSubgroupsToGroup: (params: { gid: any; generated?: string[] }) => Promise<any>;
  removeSubgroupsFromGroup: (params: { gid: any; generated?: string[] }) => Promise<any>;
  audit: (params: { generated?: any }) => Promise<any>;
  platformAnalyticReads: (params: { day?: string }) => Promise<any>;
  platformAnalyticEventSummaries: (params: { accountId?: any; generated?: any }) => Promise<any>;
  exportSolution: (params: { solutionId: string; qBLVersion?: string }) => Promise<any>;
  updateSolution: (params: { solutionId: string; generated?: any; xQBLErrorsAsSuccess?: boolean }) => Promise<any>;
  createSolution: (params: { generated?: any; xQBLErrorsAsSuccess?: boolean }) => Promise<any>;
  exportSolutionToRecord: (params: { solutionId: string; tableId: string; fieldId: number; xQBLErrorsAsSuccess?: boolean; qBLVersion?: string }) => Promise<any>;
  createSolutionFromRecord: (params: { tableId: string; fieldId: number; recordId: number; xQBLErrorsAsSuccess?: boolean }) => Promise<any>;
  updateSolutionToRecord: (params: { solutionId: string; tableId: string; fieldId: number; recordId: number; xQBLErrorsAsSuccess?: boolean }) => Promise<any>;
  changesetSolution: (params: { solutionId: string; generated?: any; xQBLErrorsAsSuccess?: boolean }) => Promise<any>;
  changesetSolutionFromRecord: (params: { solutionId: string; tableId: string; fieldId: number; recordId: number; xQBLErrorsAsSuccess?: boolean }) => Promise<any>;
  generateDocument: (params: { templateId: any; tableId: string; recordId?: any; filename: string; accept?: string; format?: string; margin?: string; unit?: string; pageSize?: string; orientation?: string; realm?: string }) => Promise<any>;
}
